#ifndef RASAL_H
#define RASAL_H

#define RASAL_NS rasal

#define RASAL_NAMESPACE_OPEN_SCOPE namespace RASAL_NS {
#define RASAL_NAMESPACE_CLOSE_SCOPE }

RASAL_NAMESPACE_OPEN_SCOPE

RASAL_NAMESPACE_CLOSE_SCOPE

#endif // RASAL_H
